### ISSUE TITLE
Delay creating the file

### ISSUE THREAD

**Issue by superern** [dvla/sqs-extended-client#11]
I got into an issue where the sqs-message is getting consumed first before the file getting created after upgrading to aws-sdk v3 and node v18.

what looks like happened here is that it send a message to SQS immediately without waiting for the file to be created.

![image](https://github.com/dvla/sqs-extended-client/assets/39351808/c3523a1e-f5a5-43aa-87df-6b1287aaa82c)
![image](https://github.com/dvla/sqs-extended-client/assets/39351808/7fcd41cf-f2ad-432b-9a61-e99b44d88a61)

**Comment by rod-dvla** [comment]
Hi @superern, thank you for raising the above issue.  It looked as if we were doint some quite complicated checks in order to provide backward compatability that may have caused the issue.  Hopefully this is resolved in v1.0.0, please send over a message if the issue persists.
